name: Run Tests and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"
          cache: "npm"

      - name: Set npm registry and increase network timeout
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retry-maxtimeout 120000

      - name: Install dependencies
        run: |
          npm install -g npm@latest
          npm install

      - name: Build
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"
          cache: "npm"

      - name: Set npm registry and increase network timeout
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retry-maxtimeout 120000

      - name: Install dependencies
        run: |
          npm install -g npm@latest
          npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy to Cloudflare Pages
        run: |
          curl -X POST "${{ secrets.CLOUDFLARE_PAGES_DEPLOY_HOOK_URL }}"
